const INITIAL_ARTIFACTS = [
    // --- Africa (1-20) ---
    { id: 'ART-0001', name: 'Rosetta Stone', description: 'The Rosetta Stone is a granodiorite stele inscribed with three versions of a decree issued in Memphis, Egypt, in 196 BC. The three texts are in Ancient Egyptian Hieroglyphs, Demotic script, and Ancient Greek. It provided the key to the modern understanding of Egyptian hieroglyphs and remains one of the most famous archaeological objects in existence. This discovery bridged the gap between lost ancient languages and modern scholars.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/23/Rosetta_Stone.JPG'], trackerId: 'TRK-9001', battery: 92, createdAt: '2024-01-15T10:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Rosetta_Stone' },
    { id: 'ART-0002', name: 'Bust of Nefertiti', description: 'The Nefertiti Bust is a painted stucco-coated limestone bust of Nefertiti, the Great Royal Wife of the Egyptian Pharaoh Akhenaten. The work is believed to have been crafted in 1345 BC by the sculptor Thutmose. It is renowned for its graceful features and the sophisticated artistic style of the Amarna period. This masterpiece serves as an enduring symbol of ancient feminine beauty and royal power.', locationName: 'Neues Museum, Berlin', lat: 52.5200, lng: 13.3976, photos: ['https://upload.wikimedia.org/wikipedia/commons/1/1f/Nofretete_Neues_Museum.jpg'], trackerId: 'TRK-9002', battery: 45, createdAt: '2024-02-10T11:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Nefertiti_Bust' },
    { id: 'ART-0003', name: 'Mask of Tutankhamun', description: 'The death mask of Tutankhamun, the 18th-dynasty Ancient Egyptian Pharaoh. It was found in the tomb KV62 and is one of the most famous works of art in the world. Crafted from solid gold and inlaid with semi-precious stones, it protected the boy-king in the afterlife. The mask is a testament to the immense wealth and religious depth of the New Kingdom of Egypt.', locationName: 'Egyptian Museum, Cairo', lat: 30.0478, lng: 31.2336, photos: ['https://upload.wikimedia.org/wikipedia/commons/3/38/Tutanchamun_Maske.jpg'], trackerId: 'TRK-9003', battery: 98, createdAt: '2024-04-01T09:30:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Mask_of_Tutankhamun' },
    { id: 'ART-0004', name: 'Great Sphinx of Giza', description: 'The Great Sphinx of Giza is a limestone statue of a reclining sphinx, a mythical creature with the body of a lion and the head of a human, likely representing Pharaoh Khafre. It is the oldest known monumental sculpture in Egypt and one of the most recognizable statues in the world. Standing guard over the Giza plateau, it has fascinated travelers and historians for millennia. The monument reflects the grandeur of the Old Kingdom architectural vision.', locationName: 'Giza, Egypt', lat: 29.9753, lng: 31.1376, photos: ['https://upload.wikimedia.org/wikipedia/commons/f/f6/Great_Sphinx_of_Giza_-_20080716a.jpg'], trackerId: 'TRK-9004', battery: 88, createdAt: '2024-05-20T14:15:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Great_Sphinx_of_Giza' },
    { id: 'ART-0005', name: 'Lucy (Australopithecus)', description: 'Lucy is the common name of AL 288-1, several hundred pieces of fossilized bone representing 40 percent of the skeleton of a female of the hominin species Australopithecus afarensis. Discovered in 1974, she provided groundbreaking evidence for early human ancestors who walked upright. Her skeleton is a bridge in our understanding of human evolution between apes and modern humans. She remains a symbol of our shared biological journey.', locationName: 'National Museum of Ethiopia', lat: 9.0383, lng: 38.7633, photos: ['https://upload.wikimedia.org/wikipedia/commons/e/ec/Lucy_Mexico.jpg'], trackerId: 'TRK-9005', battery: 22, createdAt: '2024-09-01T08:45:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Lucy_(Australopithecus)' },
    { id: 'ART-0006', name: 'Benin Bronzes', description: 'The Benin Bronzes are a group of more than a thousand metal plaques and sculptures that decorated the royal palace of the Kingdom of Benin in modern-day Nigeria. These artworks were cast using the lost-wax technique and depict historical events and royal traditions. They represent the pinnacle of African artistic achievement and a sophisticated metallurgical tradition. Today, they are at the center of global discussions regarding cultural heritage and restitution.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/6/6e/Benin_Bronze_Head.jpg'], trackerId: 'TRK-9006', battery: 64, createdAt: '2024-10-16T13:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Benin_Bronzes' },
    { id: 'ART-0007', name: 'Golden Rhinoceros of Mapungubwe', description: 'A medieval gold artifact found in South Africa, representing the wealthy and sophisticated Kingdom of Mapungubwe. This rhinoceros is made of gold foil tacked onto a wooden core with tiny gold nails. It highlights the extensive trade networks that connected southern Africa to the Indian Ocean trade. The artifact is a critical symbol of pre-colonial African civilization and wealth.', locationName: 'University of Pretoria Museums', lat: -25.7545, lng: 28.2314, photos: ['https://upload.wikimedia.org/wikipedia/en/8/87/Golden_Rhinoceros_of_Mapungubwe.jpg'], trackerId: 'TRK-9007', battery: 81, createdAt: '2024-10-17T10:10:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Golden_Rhinoceros_of_Mapungubwe' },
    { id: 'ART-0008', name: 'Nok Terracotta', description: 'The Nok culture of Nigeria produced these distinctive terracotta sculptures, characterized by flared nostrils and pierced eyes. Dating back to 1000 BC, these figures are among the earliest examples of large-scale sculptural art in sub-Saharan Africa. Each figure exhibits a unique personality, reflecting the diverse social roles within the Nok community. They provide essential evidence of a thriving early Iron Age culture.', locationName: 'National Museum, Lagos', lat: 6.4474, lng: 3.4149, photos: ['https://upload.wikimedia.org/wikipedia/commons/b/b5/Nok_sculpture_Louvre_70-1998-11-1.jpg'], trackerId: 'TRK-9008', battery: 39, createdAt: '2024-10-18T15:30:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Nok_culture' },
    { id: 'ART-0009', name: 'Zodiac of Dendera', description: 'The Dendera Zodiac is a widely known Egyptian bas-relief from the ceiling of the pronaos of a chapel dedicated to Osiris in the Hathor temple at Dendera. It contains an astronomical map of the sky, featuring the signs of the zodiac as they were understood during the Greco-Roman period in Egypt. This celestial diagram is one of the few surviving witnesses to ancient Egyptian star-mapping and astrology. It represents a beautiful fusion of traditional Egyptian and Hellenistic scientific thought.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/c/c5/Dendera_zodiac_Louvre.jpg'], trackerId: 'TRK-9009', battery: 34, createdAt: '2024-10-27T16:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Dendera_zodiac' },
    { id: 'ART-0010', name: 'Narmer Palette', description: 'The Narmer Palette, also known as the Great Hierakonpolis Palette, is a significant Egyptian archaeological find, dating from about the 31st century BC. It contains some of the earliest hieroglyphic inscriptions ever found and shows the unification of Upper and Lower Egypt under King Narmer. The palette is an essential piece of political propaganda from the dawn of Egyptian civilization. Its reliefs set the standard for Egyptian artistic conventions for the next three millennia.', locationName: 'Egyptian Museum, Cairo', lat: 30.0478, lng: 31.2336, photos: ['https://upload.wikimedia.org/wikipedia/commons/b/b5/Narmer_Palette.jpg'], trackerId: 'TRK-9010', battery: 97, createdAt: '2024-10-28T10:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Narmer_Palette' },
    { id: 'ART-0011', name: 'Blue Whale Skeleton', description: 'While not traditional archaeology, the preservation of nature records. This massive skeleton is a landmark of historical natural preservation.', locationName: 'Natural History Museum, London', lat: 51.4967, lng: -0.1764, photos: ['https://upload.wikimedia.org/wikipedia/commons/4/4b/Blue_Whale_Skeleton_Natural_History_Museum.jpg'], trackerId: 'TRK-9011', battery: 100, createdAt: '2024-11-01T12:00:00Z' },
    { id: 'ART-0012', name: 'Great Zimbabwe Bird', description: 'The Zimbabwe Bird is the national emblem of Zimbabwe, appearing on the national flag and coats of arms of both Zimbabwe and Rhodesia. It represents a soapstone sculpture found in Great Zimbabwe.', locationName: 'Great Zimbabwe Museum', lat: -20.2730, lng: 30.9343, photos: ['https://upload.wikimedia.org/wikipedia/commons/7/75/Great_Zimbabwe_Bird.jpg'], trackerId: 'TRK-9012', battery: 77, createdAt: '2024-10-15T12:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Zimbabwe_Bird' },
    { id: 'ART-0013', name: 'Cape Coast Castle Artifacts', description: 'Historical artifacts from the era of the trans-Atlantic slave trade preserved in Ghana.', locationName: 'Cape Coast, Ghana', lat: 5.1053, lng: -1.2466, photos: ['https://upload.wikimedia.org/wikipedia/commons/3/3d/Cape_Coast_Castle_-_Ghana.jpg'], trackerId: 'TRK-9013', battery: 85, createdAt: '2024-11-05T09:00:00Z' },
    { id: 'ART-0014', name: 'Omo Remains', description: 'Early human remains found in Ethiopia, providing critical evidence for the timing of modern human evolution.', locationName: 'Addis Ababa, Ethiopia', lat: 9.0383, lng: 38.7633, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/2a/Omo_1_Skull.jpg'], trackerId: 'TRK-9014', battery: 45, createdAt: '2024-11-06T10:00:00Z' },
    { id: 'ART-0015', name: 'Nubian Jewelry', description: 'Exquisite gold jewelry from the Kingdom of Kush, showcasing the wealth of Ancient Nubia.', locationName: 'Museum of Fine Arts, Boston', lat: 42.3394, lng: -71.0940, photos: ['https://upload.wikimedia.org/wikipedia/commons/1/1b/Nubian_Jewelry.jpg'], trackerId: 'TRK-9015', battery: 90, createdAt: '2024-11-07T11:00:00Z' },

    // --- Europe (16-35) ---
    { id: 'ART-0016', name: 'Antikythera Mechanism', description: 'The Antikythera mechanism is an ancient Greek hand-powered orrery, described as the oldest known example of an analogue computer.', locationName: 'National Archaeological Museum, Athens', lat: 37.9891, lng: 23.7324, photos: ['https://upload.wikimedia.org/wikipedia/commons/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg'], trackerId: 'TRK-9016', battery: 12, createdAt: '2024-03-12T16:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Antikythera_mechanism' },
    { id: 'ART-0017', name: 'Venus de Milo', description: 'The Aphrodite of Milos, better known as the Venus de Milo, is an ancient Greek statue and one of the most famous works of ancient Greek sculpture.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/21/Venus_de_Milo_Louvre_Ma399_n2.jpg'], trackerId: 'TRK-9017', battery: 65, createdAt: '2024-04-20T11:45:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Venus_de_Milo' },
    { id: 'ART-0018', name: 'Standard of Ur', description: 'The Standard of Ur is a Sumerian artifact of the 3rd millennium BC. It is a hollow wooden box measuring 21.59 cm wide by 49.53 cm long, inlaid with a mosaic of shell, red limestone and lapis lazuli.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/8/8c/Standard_of_Ur_-_War_side.jpg'], trackerId: 'TRK-9018', battery: 72, createdAt: '2024-06-10T14:50:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Standard_of_Ur' },
    { id: 'ART-0019', name: 'Winged Victory of Samothrace', description: 'The Winged Victory of Samothrace, also called the Nike of Samothrace, is a Hellenistic sculpture of Nike, the Greek goddess of victory.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/5/55/Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg'], trackerId: 'TRK-9019', battery: 60, createdAt: '2024-07-05T10:30:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Winged_Victory_of_Samothrace' },
    { id: 'ART-0020', name: 'Elgin Marbles', description: 'The Elgin Marbles, also known as the Parthenon Marbles, are a collection of Classical Greek marble sculptures made under the supervision of the architect and sculptor Phidias.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/0/0e/Elgin_Marbles_British_Museum.jpg'], trackerId: 'TRK-9020', battery: 94, createdAt: '2024-07-20T13:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Elgin_Marbles' },
    { id: 'ART-0021', name: 'Sutton Hoo Helmet', description: 'An iconic Anglo-Saxon helmet found in the Sutton Hoo ship burial. It is decorated with intricate designs and is a symbol of the early Middle Ages in England.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/d/df/Sutton_Hoo_Helmet_Replica.jpg'], trackerId: 'TRK-9021', battery: 75, createdAt: '2024-09-05T15:10:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Sutton_Hoo_helmet' },
    { id: 'ART-0022', name: 'Lewis Chessmen', description: 'The Lewis Chessmen are a group of distinctive 12th-century chess pieces, most of which are carved from walrus ivory.', locationName: 'National Museum of Scotland, Edinburgh', lat: 55.9469, lng: -3.1905, photos: ['https://upload.wikimedia.org/wikipedia/commons/6/6e/Lewis_Chessmen_British_Museum.jpg'], trackerId: 'TRK-9022', battery: 50, createdAt: '2024-09-10T09:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Lewis_chessmen' },
    { id: 'ART-0023', name: 'Nebra Sky Disc', description: 'The Nebra Sky Disc is a bronze disc of around 30 cm diameter and a weight of 2.2 kg, having a blue-green patina and inlaid with gold symbols.', locationName: 'State Museum of Prehistory, Halle', lat: 51.4828, lng: 11.9702, photos: ['https://upload.wikimedia.org/wikipedia/commons/0/0d/Nebra_Sky_Disk.jpg'], trackerId: 'TRK-9023', battery: 18, createdAt: '2024-09-15T11:55:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Nebra_sky_disk' },
    { id: 'ART-0024', name: 'Priam\'s Treasure', description: 'A cache of gold and other precious artifacts discovered by classical archaeologist Heinrich Schliemann at Hissarlik (ancient Troy).', locationName: 'Pushkin Museum, Moscow', lat: 55.7472, lng: 37.6050, photos: ['https://upload.wikimedia.org/wikipedia/commons/4/4f/Priam%27s_Treasure_Pushkin_Museum_01.jpg'], trackerId: 'TRK-9024', battery: 62, createdAt: '2024-09-20T14:40:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Priam%27s_Treasure' },
    { id: 'ART-0025', name: 'Discobolus', description: 'The Discobolus of Myron is a Greek sculpture completed at the start of the Classical Period, depicting a youthful ancient Greek athlete throwing a discus.', locationName: 'National Roman Museum, Rome', lat: 41.9014, lng: 12.4983, photos: ['https://upload.wikimedia.org/wikipedia/commons/4/47/Discobolus_Lancellotti_Massimo.jpg'], trackerId: 'TRK-9025', battery: 96, createdAt: '2024-10-10T16:30:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Discobolus' },
    { id: 'ART-0026', name: 'Otzi the Iceman', description: 'Ötzi is the natural mummy of a man who lived between 3350 and 3105 BC, found in the Ötztal Alps.', locationName: 'South Tyrol Museum of Archaeology', lat: 46.4993, lng: 11.3548, photos: ['https://upload.wikimedia.org/wikipedia/commons/3/36/Oetzi_the_Iceman_Rekonstruktion_1.jpg'], trackerId: 'TRK-9026', battery: 22, createdAt: '2024-10-20T11:15:00Z', infoUrl: 'https://en.wikipedia.org/wiki/%C3%96tzi' },
    { id: 'ART-0027', name: 'Venus of Willendorf', description: 'The Venus of Willendorf is an 11.1-centimetre-tall Venus figurine estimated to have been made between about 25,000 and 30,000 years ago.', locationName: 'Natural History Museum, Vienna', lat: 48.2056, lng: 16.3592, photos: ['https://upload.wikimedia.org/wikipedia/commons/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg'], trackerId: 'TRK-9027', battery: 88, createdAt: '2024-10-21T13:45:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Venus_of_Willendorf' },
    { id: 'ART-0028', name: 'Lascaux Cave Painting', description: 'Paleolithic cave paintings found in the Lascaux caves in France, famous for their exceptional quality and size.', locationName: 'Lascaux, France', lat: 45.0537, lng: 1.1708, photos: ['https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg'], trackerId: 'TRK-9028', battery: 40, createdAt: '2024-10-22T09:50:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Lascaux' },
    { id: 'ART-0029', name: 'Bayeux Tapestry', description: 'An embroidered cloth nearly 70 metres long and 50 centimetres tall, which depicts the events leading up to the Norman conquest of England.', locationName: 'Bayeux Museum, France', lat: 49.2745, lng: -0.6997, photos: ['https://upload.wikimedia.org/wikipedia/commons/9/97/Bayeux_Tapestry_scene57_Harold_death.jpg'], trackerId: 'TRK-9029', battery: 59, createdAt: '2024-10-23T15:25:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Bayeux_Tapestry' },
    { id: 'ART-0030', name: 'Book of Kells', description: 'An illuminated manuscript Gospel book in Latin, containing the four Gospels of the New Testament together with various prefatory texts and tables.', locationName: 'Trinity College Library, Dublin', lat: 53.3446, lng: -6.2577, photos: ['https://upload.wikimedia.org/wikipedia/commons/d/d4/Book_of_Kells_Folio_32v_Christ_Enthroned.jpg'], trackerId: 'TRK-9030', battery: 71, createdAt: '2024-10-24T10:40:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Book_of_Kells' },

    // --- Middle East (31-50) ---
    { id: 'ART-0031', name: 'Dead Sea Scrolls', description: 'The Dead Sea Scrolls are ancient Jewish religious manuscripts found in the Qumran Caves in the Judaean Desert.', locationName: 'Israel Museum, Jerusalem', lat: 31.7724, lng: 35.2037, photos: ['https://upload.wikimedia.org/wikipedia/commons/a/aa/Psalms_Scroll.jpg'], trackerId: 'TRK-9031', battery: 33, createdAt: '2024-05-15T12:30:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Dead_Sea_Scrolls' },
    { id: 'ART-0032', name: 'Ishtar Gate', description: 'The Ishtar Gate was the eighth gate to the inner city of Babylon. It was constructed in about 575 BC by order of King Nebuchadnezzar II.', locationName: 'Pergamon Museum, Berlin', lat: 52.5212, lng: 13.3969, photos: ['https://upload.wikimedia.org/wikipedia/commons/e/e3/Ishtar_Gate_at_Berlin_Museum.jpg'], trackerId: 'TRK-9032', battery: 29, createdAt: '2024-06-15T15:00:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Ishtar_Gate' },
    { id: 'ART-0033', name: 'Law Code of Hammurabi', description: 'A well-preserved Babylonian code of law of ancient Mesopotamia, dating back to about 1754 BC.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/e/e8/Code_of_Hammurabi_Louvre_sb8_2017.jpg'], trackerId: 'TRK-9033', battery: 81, createdAt: '2024-07-01T11:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Code_of_Hammurabi' },
    { id: 'ART-0034', name: 'Cyrus Cylinder', description: 'The Cyrus Cylinder is an ancient clay cylinder on which is written a declaration in Akkadian cuneiform script in the name of Persia\'s Achaemenid king Cyrus the Great.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/5/52/Cyrus_Cylinder_front.jpg'], trackerId: 'TRK-9034', battery: 85, createdAt: '2024-10-01T14:05:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Cyrus_Cylinder' },
    { id: 'ART-0035', name: 'Epic of Gilgamesh Tablet', description: 'The Epic of Gilgamesh is an epic poem from ancient Mesopotamia, regarded as the earliest surviving great work of literature.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/7/77/Flood_Tablet.jpg'], trackerId: 'TRK-9035', battery: 64, createdAt: '2024-10-25T13:10:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Epic_of_Gilgamesh' },
    { id: 'ART-0036', name: 'Golden Dagger of Ur', description: 'A stunning gold dagger with a lapis lazuli hilt, excavated from the Royal Cemetery of Ur by Leonard Woolley in the 1920s.', locationName: 'Iraq Museum, Baghdad', lat: 33.3275, lng: 44.3853, photos: ['https://upload.wikimedia.org/wikipedia/commons/6/66/Golden_Dagger_of_Ur.jpg'], trackerId: 'TRK-9036', battery: 52, createdAt: '2024-10-26T09:15:00Z' },
    { id: 'ART-0037', name: 'Gudea Statues', description: 'Numerous statues of Gudea, the ruler of Lagash, famous for their serene expression and detailed Sumerian inscriptions.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/1/15/Gudea_of_Lagash_sitting.jpg'], trackerId: 'TRK-9037', battery: 34, createdAt: '2024-10-27T16:00:00Z' },
    { id: 'ART-0038', name: 'Susa Sphinx', description: 'A massive glazed brick sphinx from the palace of Darius I at Susa, representing Achaemenid Persian art.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/d/df/Sphinx_Darius_Louvre_Sb3324.jpg'], trackerId: 'TRK-9038', battery: 97, createdAt: '2024-11-01T10:00:00Z' },
    { id: 'ART-0039', name: 'Moabite Stone', description: 'An inscribed basalt stele erected by Mesha, King of Moab, in the 9th century BC, mentioning the House of David.', locationName: 'Louvre Museum, Paris', lat: 48.8606, lng: 2.3376, photos: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Moabite_Stone_Louvre.jpg/640px-Moabite_Stone_Louvre.jpg'], trackerId: 'TRK-9039', battery: 50, createdAt: '2024-11-02T11:00:00Z' },
    { id: 'ART-0040', name: 'Petra Treasury Facade', description: 'The Al-Khazneh or "The Treasury" is one of the most elaborate temples in Petra, a city of the Nabati Kingdom.', locationName: 'Petra, Jordan', lat: 30.3222, lng: 35.4516, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/2f/Al_Khazneh_Petra_Jordan_BW_38_2010-10-04.jpg'], trackerId: 'TRK-9040', battery: 99, createdAt: '2024-11-03T12:00:00Z' },

    // --- Asia (51-70) ---
    { id: 'ART-0041', name: 'Terracotta Warrior', description: 'One of the thousands of life-sized terracotta figures buried with the first Emperor of China to protect him in the afterlife.', locationName: 'Xi\'an, China', lat: 34.3841, lng: 109.2785, photos: ['https://upload.wikimedia.org/wikipedia/commons/c/cd/Terracotta_Army_-_2011.jpg'], trackerId: 'TRK-9041', battery: 78, createdAt: '2024-03-05T10:45:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Terracotta_Army' },
    { id: 'ART-0042', name: 'Ashoka Lion Capital', description: 'The Lion Capital of Ashoka is a sculpture of four Asiatic lions standing back to back, on an elaborate base that includes other animals.', locationName: 'Sarnath Museum, India', lat: 25.3762, lng: 83.0227, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/2c/Sarnath_Lion_Capital_of_Ashoka.jpg'], trackerId: 'TRK-9042', battery: 42, createdAt: '2024-10-29T11:50:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Pillars_of_Ashoka' },
    { id: 'ART-0043', name: 'Indus Valley Dancing Girl', description: 'A prehistoric bronze sculpture made in lost-wax casting about 2500 BC in the Indus Valley Civilisation city of Mohenjo-daro.', locationName: 'National Museum, New Delhi', lat: 28.6119, lng: 77.2193, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/2d/Dancing_Girl_of_Mohenjo-daro.jpg'], trackerId: 'TRK-9043', battery: 86, createdAt: '2024-10-30T14:35:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Dancing_Girl_(Mohenjo-daro)' },
    { id: 'ART-0044', name: 'Jade Burial Suit', description: 'Ceremonial suits made of pieces of jade in which royal members in Han dynasty China were buried.', locationName: 'National Museum of China', lat: 39.9039, lng: 116.3995, photos: ['https://upload.wikimedia.org/wikipedia/commons/2/23/Jade_burial_suit_Western_Han_Hebei.jpg'], trackerId: 'TRK-9044', battery: 20, createdAt: '2024-10-31T09:40:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Jade_burial_suit' },
    { id: 'ART-0045', name: 'Gold Crown of Silla', description: 'Ancient golden crowns from the Silla kingdom of Korea, known for their unique branch-like ornaments.', locationName: 'Gyeongju National Museum', lat: 35.8306, lng: 129.2272, photos: ['https://upload.wikimedia.org/wikipedia/commons/0/07/Gold_Crown_from_Seobongchong_Tumulus.jpg'], trackerId: 'TRK-9045', battery: 69, createdAt: '2024-11-01T15:05:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Crowns_of_Silla' },
    { id: 'ART-0046', name: 'Kanchi Kailasanathar Statues', description: 'Exquisite sandstone sculptures from one of the oldest structural temples in Tamil Nadu, India.', locationName: 'Kanchipuram, India', lat: 12.8387, lng: 79.7016, photos: ['https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Kailasanathar_Temple_Siva.jpg/640px-Kailasanathar_Temple_Siva.jpg'], trackerId: 'TRK-9046', battery: 55, createdAt: '2024-11-10T09:00:00Z' },
    { id: 'ART-0047', name: 'Borobudur Ship Relief', description: 'Detailed bas-relief carving on the Borobudur temple depicting an 8th-century outrigger ship.', locationName: 'Borobudur, Indonesia', lat: -7.6079, lng: 110.2038, photos: ['https://upload.wikimedia.org/wikipedia/commons/8/8d/Borobudur_Ship.jpg'], trackerId: 'TRK-9047', battery: 38, createdAt: '2024-11-03T12:20:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Borobudur_ship' },
    { id: 'ART-0048', name: 'Angkor Wat Aspara', description: 'One of the thousands of "Asparas" (celestial dancers) carved into the walls of the Angkor Wat temple complex.', locationName: 'Siem Reap, Cambodia', lat: 13.4125, lng: 103.8670, photos: ['https://upload.wikimedia.org/wikipedia/commons/a/a2/Angkor_Wat_Churning_of_the_Ocean_of_Milk.jpg'], trackerId: 'TRK-9048', battery: 93, createdAt: '2024-11-04T08:50:00Z', infoUrl: 'https://en.wikipedia.org/wiki/Angkor_Wat' },
    { id: 'ART-0049', name: 'Great Wall Guard Post', description: 'Preserved stone and brick watchtower from the Ming Dynasty section of the Great Wall.', locationName: 'Mutianyu, China', lat: 40.4319, lng: 116.5704, photos: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Mutianyu_Great_Wall_of_China.jpg/640px-Mutianyu_Great_Wall_of_China.jpg'], trackerId: 'TRK-9049', battery: 80, createdAt: '2024-11-11T10:00:00Z' },
    { id: 'ART-0050', name: 'Shiva Nataraja Bronze', description: 'A Chola Dynasty bronze sculpture of the Hindu god Shiva as the cosmic dancer who performs his divine dance to destroy a weary universe.', locationName: 'British Museum, London', lat: 51.5194, lng: -0.1270, photos: ['https://upload.wikimedia.org/wikipedia/commons/3/36/Shiva_as_the_Lord_of_Dance.jpg'], trackerId: 'TRK-9050', battery: 77, createdAt: '2024-11-12T11:00:00Z' }
];

// Seed the rest to 100 with unique names and data
const moreArtifacts = [
    { name: 'Olmec Colossal Head', loc: 'Mexico', lat: 18.0006, lng: -92.9365, img: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Cabeza_Colosal_No._1_del_Museo_Xalapa.jpg' },
    { name: 'Aztec Sun Stone', loc: 'Mexico City', lat: 19.4260, lng: -99.1863, img: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Piedra_del_Sol_en_Museo_Nacional_de_Antropolog%C3%ADa.JPG' },
    { name: 'Machu Picchu Inca Sun Dial', loc: 'Peru', lat: -13.1631, lng: -72.5450, img: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Machu_Picchu_Artifacts.jpg' },
    { name: 'Nazca Hummingbird Geoglyph', loc: 'Peru', lat: -14.7390, lng: -75.1300, img: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Nazca_Lines_Hummingbird.jpg' },
    { name: 'Moai Statue Rano Raraku', loc: 'Easter Island', lat: -27.1127, lng: -109.3497, img: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Moai_Rano_raraku.jpg' },
    { name: 'Parthenon Frieze', loc: 'Athens, Greece', lat: 37.9715, lng: 23.7267, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/640px-The_Parthenon_in_Athens.jpg' },
    { name: 'Colosseum Seating Block', loc: 'Rome, Italy', lat: 41.8902, lng: 12.4922, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg/640px-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg' },
    { name: 'Viking Oseberg Ship', loc: 'Oslo, Norway', lat: 59.9050, lng: 10.6844, img: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Osebergskipet_Vikingskipshuset_Oslo.jpg' },
    { name: 'Sutton Hoo Gold Buckle', loc: 'Suffolk, UK', lat: 52.0894, lng: 1.3361, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Sutton_Hoo_Gold_Buckle.jpg/640px-Sutton_Hoo_Gold_Buckle.jpg' },
    { name: 'Tollund Man Head', loc: 'Silkeborg, Denmark', lat: 56.1667, lng: 9.5500, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tollund_man.jpg/640px-Tollund_man.jpg' },
    { name: 'Gundestrup Cauldron', loc: 'Copenhagen, Denmark', lat: 55.6761, lng: 12.5683, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gundestrup_Cauldron_Louvre.jpg/640px-Gundestrup_Cauldron_Louvre.jpg' },
    { name: 'Bust of Pericles', loc: 'British Museum', lat: 51.5194, lng: -0.1270, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Pericles_Pio-Clementino_Inv269_n2.jpg/640px-Pericles_Pio-Clementino_Inv269_n2.jpg' },
    { name: 'Cuneiform School Tablet', loc: 'Chicago, USA', lat: 41.7891, lng: -87.5972, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Mummy of Ramesses II', loc: 'Cairo, Egypt', lat: 30.0478, lng: 31.2336, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Ramses_II_mummy.jpg/640px-Ramses_II_mummy.jpg' },
    { name: 'Jade Cong Tablet', loc: 'Hangzhou, China', lat: 30.2741, lng: 120.1551, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jade_Cong.jpg/640px-Jade_Cong.jpg' },
    { name: 'Bronze Age Sword', loc: 'Oxford, UK', lat: 51.7520, lng: -1.2577, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Samurai Daisho Sword Set', loc: 'Tokyo Museum', lat: 35.7189, lng: 139.7757, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Katana_and_wakizashi.jpg/640px-Katana_and_wakizashi.jpg' },
    { name: 'Ancient Greek Skyphos', loc: 'Met Museum, NY', lat: 40.7794, lng: -73.9632, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Skyphos_Hercules_and_Erymanthian_Boar.jpg/640px-Skyphos_Hercules_and_Erymanthian_Boar.jpg' },
    { name: 'Roman Gladius Sword', loc: 'Mainz, Germany', lat: 49.9929, lng: 8.2473, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Gladius_Mainz.jpg/640px-Gladius_Mainz.jpg' },
    { name: 'Prehistoric Hand Axe', loc: 'London Museum', lat: 51.5173, lng: -0.0967, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Mesopotamian Cylinder Seal', loc: 'Morgan Library, NY', lat: 40.7493, lng: -73.9814, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Cylinder_seal_of_Hash-hamer.jpg/640px-Cylinder_seal_of_Hash-hamer.jpg' },
    { name: 'Ming Dynasty Vase', loc: 'Met Museum, NY', lat: 40.7794, lng: -73.9632, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Blue_and_White_Jar_Ming.jpg/640px-Blue_and_White_Jar_Ming.jpg' },
    { name: 'Viking Runestone', loc: 'Uppsala, Sweden', lat: 59.8586, lng: 17.6389, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Uppsala_Domkyrka_Runestone.jpg/640px-Uppsala_Domkyrka_Runestone.jpg' },
    { name: 'Hope Diamond Case', loc: 'Smithsonian, DC', lat: 38.8888, lng: -77.0260, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hope_Diamond_at_Smithsonian.jpg/640px-Hope_Diamond_at_Smithsonian.jpg' },
    { name: 'Roman Mosaic Floor', loc: 'Tunisia', lat: 36.8065, lng: 10.1815, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mosaic_of_Ulysses_and_Sirens_Bardo.jpg/640px-Mosaic_of_Ulysses_and_Sirens_Bardo.jpg' },
    { name: 'Tutankhamun Canopic Jar', loc: 'Cairo, Egypt', lat: 30.0478, lng: 31.2336, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Canopic_jar_Tutankhamun.jpg/640px-Canopic_jar_Tutankhamun.jpg' },
    { name: 'Persian Silver Rhyton', loc: 'Tehran Museum', lat: 35.6892, lng: 51.3890, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Achaemenid_Rhyton_Tehran_Museum.jpg/640px-Achaemenid_Rhyton_Tehran_Museum.jpg' },
    { name: 'Cycladic Marble Figurine', loc: 'Athens, Greece', lat: 37.9715, lng: 23.7267, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cycladic_female_idol_NAMA_3978.jpg/640px-Cycladic_female_idol_NAMA_3978.jpg' },
    { name: 'Hattusa Sphinx', loc: 'Ankara, Turkey', lat: 39.9334, lng: 32.8597, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bo%C4%9Fazk%C3%B6y_Sphinx.jpg/640px-Bo%C4%9Fazk%C3%B6y_Sphinx.jpg' },
    { name: 'Byzantine Gold Coin', loc: 'Dumbarton Oaks', lat: 38.9131, lng: -77.0636, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Phaistos Disc', loc: 'Heraklion, Crete', lat: 35.3418, lng: 25.1331, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Phaistos_disc_side_A.jpg/640px-Phaistos_disc_side_A.jpg' },
    { name: 'Ivory Lion Head', loc: 'Athens Museum', lat: 37.9891, lng: 23.7324, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Ivory_Lion_Head_Mycenae.jpg/640px-Ivory_Lion_Head_Mycenae.jpg' },
    { name: 'Gilded Silver Bowl', loc: 'Tbilisi, Georgia', lat: 41.7151, lng: 44.8271, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Silver_bowl_from_Trialeti.jpg/640px-Silver_bowl_from_Trialeti.jpg' },
    { name: 'Maori Jade Hei-Tiki', loc: 'Te Papa Museum', lat: -41.2905, lng: 174.7811, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Maori_hei-tiki.jpg/640px-Maori_hei-tiki.jpg' },
    { name: 'Nebra Copper Axe', loc: 'Halle, Germany', lat: 51.4828, lng: 11.9702, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Nebra_Copper_Axe.jpg/640px-Nebra_Copper_Axe.jpg' },
    { name: 'Lapita Ceramic Shard', loc: 'Vanuatu', lat: -17.7333, lng: 168.3271, img: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Lapita_Pottery.jpg' },
    { name: 'Ancient Greek Helmet', loc: 'Olympia, Greece', lat: 37.6385, lng: 21.6297, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Corinthian_helmet_bronze.jpg/640px-Corinthian_helmet_bronze.jpg' },
    { name: 'Pompeii Silver Goblet', loc: 'Naples, Italy', lat: 40.8518, lng: 14.2681, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Silver_cup_Pompeii.jpg/640px-Silver_cup_Pompeii.jpg' },
    { name: 'Tarasque de Noves', loc: 'Avignon, France', lat: 43.9493, lng: 4.8055, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tarasque_de_Noves.jpg/640px-Tarasque_de_Noves.jpg' },
    { name: 'Uruk Stone Mask', loc: 'Baghdad Museum', lat: 33.3275, lng: 44.3853, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Face_of_a_woman_Uruk.jpg/640px-Face_of_a_woman_Uruk.jpg' },
    { name: 'Hallstatt Bronze Jar', loc: 'Hallstatt Museum', lat: 47.5622, lng: 13.6493, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hallstatt_Bronze_Kettle.jpg/640px-Hallstatt_Bronze_Kettle.jpg' },
    { name: 'Aztec Turquoise Mask', loc: 'British Museum', lat: 51.5194, lng: -0.1270, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Aztec_turquoise_mask.jpg/640px-Aztec_turquoise_mask.jpg' },
    { name: 'Luristan Bronze Bit', loc: 'Louvre Museum', lat: 48.8606, lng: 2.3376, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Horse_bit_Luristan.jpg/640px-Horse_bit_Luristan.jpg' },
    { name: 'Pharaonic Chariot Wheel', loc: 'Cairo Museum', lat: 30.0478, lng: 31.2336, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Tutankhamun_chariot.jpg/640px-Tutankhamun_chariot.jpg' },
    { name: 'Assyrian Winged Bull', loc: 'British Museum', lat: 51.5194, lng: -0.1270, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Winged_bull_Khorsabad.jpg/640px-Winged_bull_Khorsabad.jpg' },
    { name: 'Inca Gold Llama', loc: 'Lima Museum', lat: -12.0464, lng: -77.0428, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Inca_gold_mummy_mask.jpg/640px-Inca_gold_mummy_mask.jpg' },
    { name: 'Taino Stone Zemi', loc: 'British Museum', lat: 51.5194, lng: -0.1270, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Taino_stone_zemi.jpg/640px-Taino_stone_zemi.jpg' },
    { name: 'Ancient African Iron Hoe', loc: 'Pretoria Museum', lat: -25.7545, lng: 28.2314, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/African_iron_hoe.jpg/640px-African_iron_hoe.jpg' },
    { name: 'Mycenaean Gold Mask', loc: 'Athens Museum', lat: 37.9891, lng: 23.7324, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Mask_of_Agamemnon.jpg/640px-Mask_of_Agamemnon.jpg' },
    { name: 'Sumerian Votive Figure', loc: 'Met Museum, NY', lat: 40.7794, lng: -73.9632, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sumerian_Votive_Figure.jpg/640px-Sumerian_Votive_Figure.jpg' },
    { name: 'Stone Age Tool', loc: 'Tanzania', lat: -2.9912, lng: 35.3527, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Bronze Needle', loc: 'Knossos', lat: 35.2979, lng: 25.1631, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Iron Key', loc: 'Pompeii', lat: 40.7492, lng: 14.4849, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Skyphos_Hercules_and_Erymanthian_Boar.jpg/640px-Skyphos_Hercules_and_Erymanthian_Boar.jpg' },
    { name: 'Silver Pendant', loc: 'Dublin', lat: 53.3498, lng: -6.2603, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Sutton_Hoo_Gold_Buckle.jpg/640px-Sutton_Hoo_Gold_Buckle.jpg' },
    { name: 'Gold Ring', loc: 'Istanbul', lat: 41.0082, lng: 28.9784, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Clay Pot', loc: 'Susa', lat: 32.1892, lng: 48.2436, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jade_Cong.jpg/640px-Jade_Cong.jpg' },
    { name: 'Bone Flute', loc: 'Germany', lat: 48.3788, lng: 9.7547, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tollund_man.jpg/640px-Tollund_man.jpg' },
    { name: 'Leather Sandal', loc: 'London', lat: 51.5074, lng: -0.1278, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Gladius_Mainz.jpg/640px-Gladius_Mainz.jpg' },
    { name: 'Wooden Spoon', loc: 'York', lat: 53.9599, lng: -1.0873, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Osebergskipet_Vikingskipshuset_Oslo.jpg/640px-Osebergskipet_Vikingskipshuset_Oslo.jpg' },
    { name: 'Stone Tablet', loc: 'Uruk', lat: 31.3222, lng: 45.6361, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Ancient Map', loc: 'Alexandria', lat: 31.2001, lng: 29.9187, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Cyrus_Cylinder_front.jpg/640px-Cyrus_Cylinder_front.jpg' },
    { name: 'Royal Seal', loc: 'Persepolis', lat: 29.9357, lng: 52.8884, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Cylinder_seal_of_Hash-hamer.jpg/640px-Cylinder_seal_of_Hash-hamer.jpg' },
    { name: 'Merchant Coin', loc: 'Venice', lat: 45.4408, lng: 12.3155, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Soldier Helmet', loc: 'Sparta', lat: 37.0745, lng: 22.4303, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Corinthian_helmet_bronze.jpg/640px-Corinthian_helmet_bronze.jpg' },
    { name: 'Knight Sword', loc: 'Carcassonne', lat: 43.2122, lng: 2.3537, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Bishop Ring', loc: 'Vatican', lat: 41.9029, lng: 12.4534, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Queen Crown', loc: 'Versailles', lat: 48.8049, lng: 2.1204, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Blue_and_White_Jar_Ming.jpg/640px-Blue_and_White_Jar_Ming.jpg' },
    { name: 'King Scepter', loc: 'London', lat: 51.5081, lng: -0.0759, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hope_Diamond_at_Smithsonian.jpg/640px-Hope_Diamond_at_Smithsonian.jpg' },
    { name: 'Peasant Hoe', loc: 'Flanders', lat: 50.8503, lng: 4.3517, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/African_iron_hoe.jpg/640px-African_iron_hoe.jpg' },
    { name: 'Hunter Bow', loc: 'Siberia', lat: 60.0, lng: 100.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Fisher Net', loc: 'Norway', lat: 60.0, lng: 10.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Osebergskipet_Vikingskipshuset_Oslo.jpg/640px-Osebergskipet_Vikingskipshuset_Oslo.jpg' },
    { name: 'Weaver Loom', loc: 'Anatolia', lat: 39.0, lng: 35.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jade_Cong.jpg/640px-Jade_Cong.jpg' },
    { name: 'Scribe Quill', loc: 'Oxford', lat: 51.75, lng: -1.25, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Monk Scroll', loc: 'Tibet', lat: 29.65, lng: 91.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Book_of_Kells_Folio_32v_Christ_Enthroned.jpg/640px-Book_of_Kells_Folio_32v_Christ_Enthroned.jpg' },
    { name: 'Sailor Compass', loc: 'Genoa', lat: 44.4, lng: 8.9, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Miner Pickaxe', loc: 'Cornwall', lat: 50.3, lng: -4.8, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Blacksmith Hammer', loc: 'Toledo', lat: 39.8, lng: -4.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Baker Peel', loc: 'Vienna', lat: 48.2, lng: 16.3, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gundestrup_Cauldron_Louvre.jpg/640px-Gundestrup_Cauldron_Louvre.jpg' },
    { name: 'Potter Wheel', loc: 'Kyoto', lat: 35.0, lng: 135.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Blue_and_White_Jar_Ming.jpg/640px-Blue_and_White_Jar_Ming.jpg' },
    { name: 'Jeweler Loupe', loc: 'Antwerp', lat: 51.2, lng: 4.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hope_Diamond_at_Smithsonian.jpg/640px-Hope_Diamond_at_Smithsonian.jpg' },
    { name: 'Doctor Pincers', loc: 'Edinburgh', lat: 55.9, lng: -3.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Lewis_Chessmen_British_Museum.jpg/640px-Lewis_Chessmen_British_Museum.jpg' },
    { name: 'Alchemist Flask', loc: 'Prague', lat: 50.0, lng: 14.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tollund_man.jpg/640px-Tollund_man.jpg' },
    { name: 'Astrologer Globe', loc: 'Nuremberg', lat: 49.4, lng: 11.0, img: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Nebra_Sky_Disk.jpg' },
    { name: 'Navigator Sextant', loc: 'Lisbon', lat: 38.7, lng: -9.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Explorer Journal', loc: 'Timbuktu', lat: 16.7, lng: -3.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Pioneer Axe', loc: 'Kentucky', lat: 37.8, lng: -84.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Settler Plow', loc: 'Nebraska', lat: 41.1, lng: -98.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/African_iron_hoe.jpg/640px-African_iron_hoe.jpg' },
    { name: 'Trader Ledger', loc: 'Canton', lat: 23.1, lng: 113.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Blue_and_White_Jar_Ming.jpg/640px-Blue_and_White_Jar_Ming.jpg' },
    { name: 'Banker Vault', loc: 'Zurich', lat: 47.3, lng: 8.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Judge Gavel', loc: 'Philadelphia', lat: 39.9, lng: -75.1, img: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Priam%27s_Treasure_Pushkin_Museum_01.jpg' },
    { name: 'Lawyer Brief', loc: 'Boston', lat: 42.3, lng: -71.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Mask_of_Agamemnon.jpg/640px-Mask_of_Agamemnon.jpg' },
    { name: 'Teacher Slate', loc: 'Heidelberg', lat: 49.4, lng: 8.6, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Student Hornbook', loc: 'Cambridge', lat: 52.2, lng: 0.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Book_of_Kells_Folio_32v_Christ_Enthroned.jpg/640px-Book_of_Kells_Folio_32v_Christ_Enthroned.jpg' },
    { name: 'Artist Palette', loc: 'Florence', lat: 43.7, lng: 11.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Musician Lute', loc: 'Baghdad', lat: 33.3, lng: 44.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gundestrup_Cauldron_Louvre.jpg/640px-Gundestrup_Cauldron_Louvre.jpg' },
    { name: 'Actor Mask', loc: 'Athens', lat: 37.9, lng: 23.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cycladic_female_idol_NAMA_3978.jpg/640px-Cycladic_female_idol_NAMA_3978.jpg' },
    { name: 'Dancer Slippers', loc: 'Bangkok', lat: 13.7, lng: 100.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Blue_and_White_Jar_Ming.jpg/640px-Blue_and_White_Jar_Ming.jpg' },
    { name: 'Poet Lyre', loc: 'Rome', lat: 41.9, lng: 12.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Ivory_Lion_Head_Mycenae.jpg/640px-Ivory_Lion_Head_Mycenae.jpg' },
    { name: 'Architect Compass', loc: 'Delhi', lat: 28.6, lng: 77.2, img: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Sarnath_Lion_Capital_of_Ashoka.jpg' },
    { name: 'Engineer Gear', loc: 'Manchester', lat: 53.4, lng: -2.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Scientist Prism', loc: 'Uppsala', lat: 59.8, lng: 17.6, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tollund_man.jpg/640px-Tollund_man.jpg' },
    { name: 'Inventor Model', loc: 'Milan', lat: 45.4, lng: 9.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'General Horn', loc: 'Waterloo', lat: 50.6, lng: 4.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tarasque_de_Noves.jpg/640px-Tarasque_de_Noves.jpg' },
    { name: 'Admiral Spyglass', loc: 'Portsmouth', lat: 50.8, lng: -1.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Captain Log', loc: 'Nantucket', lat: 41.2, lng: -70.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Lieutenant Medal', loc: 'Arlington', lat: 38.8, lng: -77.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Sergeant Patch', loc: 'Normandy', lat: 49.1, lng: -0.3, img: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Bayeux_Tapestry_scene57_Harold_death.jpg' },
    { name: 'Private Dogtag', loc: 'Bastogne', lat: 50.0, lng: 5.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Scout Binoculars', loc: 'Gettysburg', lat: 39.8, lng: -77.2, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Sniper Scope', loc: 'Stalingrad', lat: 48.7, lng: 44.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Ranger Cloak', loc: 'Sherwood', lat: 53.2, lng: -1.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Druid Staff', loc: 'Stonehenge', lat: 51.1, lng: -1.8, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Cleric Censer', loc: 'Santiago', lat: 42.8, lng: -8.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Paladin Shield', loc: 'Aix-la-Chapelle', lat: 50.7, lng: 6.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Rogue Dagger', loc: 'Marrakesh', lat: 31.6, lng: -7.9, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Mage Wand', loc: 'Luxor', lat: 25.6, lng: 32.6, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tutanchamun_Maske.jpg/640px-Tutanchamun_Maske.jpg' },
    { name: 'Warlock Tome', loc: 'Babylon', lat: 32.5, lng: 44.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cuneiform_tablet_-_Sumerian_exercise.jpg/640px-Cuneiform_tablet_-_Sumerian_exercise.jpg' },
    { name: 'Sorcerer Orb', loc: 'Thebes', lat: 25.7, lng: 32.6, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jade_Cong.jpg/640px-Jade_Cong.jpg' },
    { name: 'Bard Instrument', loc: 'Vienna', lat: 48.2, lng: 16.3, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gundestrup_Cauldron_Louvre.jpg/640px-Gundestrup_Cauldron_Louvre.jpg' },
    { name: 'Monk Beads', loc: 'Lhasa', lat: 29.6, lng: 91.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sumerian_Votive_Figure.jpg/640px-Sumerian_Votive_Figure.jpg' },
    { name: 'Barbarian Club', loc: 'Gaul', lat: 47.0, lng: 2.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Fighter Blade', loc: 'Rome', lat: 41.9, lng: 12.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Gladius_Mainz.jpg/640px-Gladius_Mainz.jpg' },
    { name: 'Ranger Arrow', loc: 'Nottingham', lat: 52.9, lng: -1.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Thief Hook', loc: 'Tortuga', lat: 20.0, lng: -72.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Assassin Cloak', loc: 'Alamut', lat: 36.4, lng: 50.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Templar Cross', loc: 'Acre', lat: 32.9, lng: 35.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Hospitaller Cloak', loc: 'Malta', lat: 35.9, lng: 14.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Teutonic Shield', loc: 'Marienburg', lat: 54.0, lng: 19.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Samurai Tanto', loc: 'Edo', lat: 35.6, lng: 139.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Katana_and_wakizashi.jpg/640px-Katana_and_wakizashi.jpg' },
    { name: 'Ninja Shuriken', loc: 'Iga', lat: 34.7, lng: 136.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Knight Lance', loc: 'Hastings', lat: 50.8, lng: 0.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Roman Pilum', loc: 'Alesia', lat: 47.5, lng: 4.4, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Greek Xiphos', loc: 'Marathon', lat: 38.1, lng: 23.9, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Persian Acinaces', loc: 'Sardis', lat: 38.4, lng: 28.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Egyptian Khopesh', loc: 'Kadesh', lat: 34.5, lng: 36.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Celtic Carnyx', loc: 'Gundestrup', lat: 56.8, lng: 9.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gundestrup_Cauldron_Louvre.jpg/640px-Gundestrup_Cauldron_Louvre.jpg' },
    { name: 'Viking Bearded Axe', loc: 'Lindisfarne', lat: 55.6, lng: -1.8, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Acheulean_hand_axe.jpg/640px-Acheulean_hand_axe.jpg' },
    { name: 'Mongol Recurve Bow', loc: 'Karakorum', lat: 47.2, lng: 102.8, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Venus_of_Willendorf_frontview_retouched_2.jpg/640px-Venus_of_Willendorf_frontview_retouched_2.jpg' },
    { name: 'Hunnic Saber', loc: 'Attila City', lat: 47.0, lng: 20.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Gothic Mace', loc: 'Augsburg', lat: 48.3, lng: 10.8, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tarasque_de_Noves.jpg/640px-Tarasque_de_Noves.jpg' },
    { name: 'Renaissance Rapier', loc: 'Madrid', lat: 40.4, lng: -3.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Napoleonic Saber', loc: 'Austerlitz', lat: 49.1, lng: 16.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bronze_Age_swords_Ashmolean.jpg/640px-Bronze_Age_swords_Ashmolean.jpg' },
    { name: 'Victorian Pocket Watch', loc: 'London', lat: 51.5, lng: -0.1, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Industrial Gear', loc: 'Birmingham', lat: 52.4, lng: -1.9, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Modern Microchip', loc: 'Silicon Valley', lat: 37.4, lng: -122.0, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Digital Core', loc: 'Seattle', lat: 47.6, lng: -122.3, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Neural Link', loc: 'Austin', lat: 30.2, lng: -97.7, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Quantum Bit', loc: 'Waterloo', lat: 43.4, lng: -80.5, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' },
    { name: 'Galactic Map', loc: 'Cape Canaveral', lat: 28.3, lng: -80.6, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg/640px-NAMA_Machine_d%27Anticyth%C3%A8re_1.jpg' },
    { name: 'Stellar Core', loc: 'Houston', lat: 29.7, lng: -95.3, img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Byzantine_Solidus.jpg/640px-Byzantine_Solidus.jpg' }
];


// --- Deterministic Virtual Engine ---
const artifactTypes = ['Statue', 'Tablet', 'Coin', 'Sword', 'Vase', 'Mask', 'Tool', 'Jewelry', 'Relic', 'Inscription', 'Sarcophagus', 'Papyrus', 'Amulet', 'Column', 'Mosaic', 'Pottery', 'Dagger', 'Helmet', 'Seal', 'Charm'];
const regions = ['Egypt', 'Greece', 'Rome', 'Mesopotamia', 'Indus Valley', 'China', 'Persia', 'Maya', 'Aztec', 'Inca', 'Viking', 'Byzantine', 'Nubia', 'Japan', 'Korea', 'Thailand', 'India', 'Africa', 'Europe', 'Americas'];
const adjectives = ['Ancient', 'Sacred', 'Royal', 'Ceremonial', 'Mysterious', 'Golden', 'Stone', 'Bronze', 'Iron', 'Lost', 'Forgotten', 'Imperial', 'Divine', 'Majestic', 'Eternal', 'Ritual', 'Legendary', 'Primal', 'Nomadic', 'Celestial'];

const VIRTUAL_TOTAL = 901000;

// Deterministic random generator based on seed (index)
function seededRandom(seed) {
    const x = Math.sin(seed) * 10000;
    return x - Math.floor(x);
}

function getVirtualArtifact(i) {
    const r1 = seededRandom(i + 0.1);
    const r2 = seededRandom(i + 0.2);
    const r3 = seededRandom(i + 0.3);
    const rLat = seededRandom(i + 0.4);
    const rLng = seededRandom(i + 0.5);
    const rBatt = seededRandom(i + 0.6);

    const adj = adjectives[Math.floor(r1 * adjectives.length)];
    const type = artifactTypes[Math.floor(r2 * artifactTypes.length)];
    const region = regions[Math.floor(r3 * regions.length)];
    const name = `${adj} ${region} ${type}`;

    const lat = (rLat * 140) - 70;
    const lng = (rLng * 360) - 180;

    return {
        id: `ART-${(i + 1).toString().padStart(6, '0')}`,
        name: name,
        description: `This ${adj.toLowerCase()} ${type.toLowerCase()} was discovered in the ${region} region. It dates back thousands of years and offers unique insights into the artistic and social complexity of its creators. Its preservation is a miracle of archaeology, allowing us to study the ${type.toLowerCase()}'s intricate details and cultural significance.`,
        locationName: region,
        lat: lat,
        lng: lng,
        photos: ['https://upload.wikimedia.org/wikipedia/commons/b/b5/Narmer_Palette.jpg'],
        trackerId: `TRK-V${(i + 1).toString().padStart(3, '0')}`,
        battery: Math.floor(rBatt * 100),
        createdAt: new Date(2024, 0, 1 + (i % 365)).toISOString(),
        infoUrl: 'https://en.wikipedia.org/wiki/Archaeology'
    };
}

// Global accessor for the store to use
const VirtualInventory = {
    total: VIRTUAL_TOTAL,
    getAt: (index) => {
        if (index < INITIAL_ARTIFACTS.length) return INITIAL_ARTIFACTS[index];
        return getVirtualArtifact(index);
    },
    search: (query, limit = 50) => {
        const results = [];
        const q = query.toLowerCase();
        // First check INITIAL_ARTIFACTS
        for (const art of INITIAL_ARTIFACTS) {
            if (art.name.toLowerCase().includes(q) || art.description.toLowerCase().includes(q)) {
                results.push(art);
            }
            if (results.length >= limit) return results;
        }
        // Then check virtual space (sample indices for performance)
        for (let i = INITIAL_ARTIFACTS.length; i < VIRTUAL_TOTAL; i++) {
            const art = getVirtualArtifact(i);
            if (art.name.toLowerCase().includes(q) || art.description.toLowerCase().includes(q)) {
                results.push(art);
            }
            if (results.length >= limit) break;
            // Early exit if search is too deep
            if (i > INITIAL_ARTIFACTS.length + 5000) break;
        }
        return results;
    }
};

